/**
 * NHK API v2
 * JavaScript client for NHK Program Guide API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetProgramsNowOnAir200ResponseNowonairListG1 from './GetProgramsNowOnAir200ResponseNowonairListG1';

/**
 * The GetProgramsNowOnAir200ResponseNowonairList model module.
 * @module model/GetProgramsNowOnAir200ResponseNowonairList
 * @version 1.0.0
 */
class GetProgramsNowOnAir200ResponseNowonairList {
    /**
     * Constructs a new <code>GetProgramsNowOnAir200ResponseNowonairList</code>.
     * @alias module:model/GetProgramsNowOnAir200ResponseNowonairList
     * @param g1 {module:model/GetProgramsNowOnAir200ResponseNowonairListG1} 
     */
    constructor(g1) { 
        
        GetProgramsNowOnAir200ResponseNowonairList.initialize(this, g1);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, g1) { 
        obj['g1'] = g1;
    }

    /**
     * Constructs a <code>GetProgramsNowOnAir200ResponseNowonairList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProgramsNowOnAir200ResponseNowonairList} obj Optional instance to populate.
     * @return {module:model/GetProgramsNowOnAir200ResponseNowonairList} The populated <code>GetProgramsNowOnAir200ResponseNowonairList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetProgramsNowOnAir200ResponseNowonairList();

            if (data.hasOwnProperty('g1')) {
                obj['g1'] = GetProgramsNowOnAir200ResponseNowonairListG1.constructFromObject(data['g1']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GetProgramsNowOnAir200ResponseNowonairListG1} g1
 */
GetProgramsNowOnAir200ResponseNowonairList.prototype['g1'] = undefined;






export default GetProgramsNowOnAir200ResponseNowonairList;

