/**
 * NHK API v2
 * JavaScript client for NHK Program Guide API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetProgramsNowOnAir200ResponseNowonairList from './GetProgramsNowOnAir200ResponseNowonairList';

/**
 * The GetProgramsNowOnAir200Response model module.
 * @module model/GetProgramsNowOnAir200Response
 * @version 1.0.0
 */
class GetProgramsNowOnAir200Response {
    /**
     * Constructs a new <code>GetProgramsNowOnAir200Response</code>.
     * @alias module:model/GetProgramsNowOnAir200Response
     * @param nowonairList {module:model/GetProgramsNowOnAir200ResponseNowonairList} 
     */
    constructor(nowonairList) { 
        
        GetProgramsNowOnAir200Response.initialize(this, nowonairList);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nowonairList) { 
        obj['nowonair_list'] = nowonairList;
    }

    /**
     * Constructs a <code>GetProgramsNowOnAir200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProgramsNowOnAir200Response} obj Optional instance to populate.
     * @return {module:model/GetProgramsNowOnAir200Response} The populated <code>GetProgramsNowOnAir200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetProgramsNowOnAir200Response();

            if (data.hasOwnProperty('nowonair_list')) {
                obj['nowonair_list'] = GetProgramsNowOnAir200ResponseNowonairList.constructFromObject(data['nowonair_list']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GetProgramsNowOnAir200ResponseNowonairList} nowonair_list
 */
GetProgramsNowOnAir200Response.prototype['nowonair_list'] = undefined;






export default GetProgramsNowOnAir200Response;

