/**
 * NHK API v2
 * JavaScript client for NHK Program Guide API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Program from './Program';

/**
 * The GetProgramsNowOnAir200ResponseNowonairListG1 model module.
 * @module model/GetProgramsNowOnAir200ResponseNowonairListG1
 * @version 1.0.0
 */
class GetProgramsNowOnAir200ResponseNowonairListG1 {
    /**
     * Constructs a new <code>GetProgramsNowOnAir200ResponseNowonairListG1</code>.
     * @alias module:model/GetProgramsNowOnAir200ResponseNowonairListG1
     * @param previous {module:model/Program} 
     * @param present {module:model/Program} 
     * @param following {module:model/Program} 
     */
    constructor(previous, present, following) { 
        
        GetProgramsNowOnAir200ResponseNowonairListG1.initialize(this, previous, present, following);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, previous, present, following) { 
        obj['previous'] = previous;
        obj['present'] = present;
        obj['following'] = following;
    }

    /**
     * Constructs a <code>GetProgramsNowOnAir200ResponseNowonairListG1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProgramsNowOnAir200ResponseNowonairListG1} obj Optional instance to populate.
     * @return {module:model/GetProgramsNowOnAir200ResponseNowonairListG1} The populated <code>GetProgramsNowOnAir200ResponseNowonairListG1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetProgramsNowOnAir200ResponseNowonairListG1();

            if (data.hasOwnProperty('previous')) {
                obj['previous'] = Program.constructFromObject(data['previous']);
            }
            if (data.hasOwnProperty('present')) {
                obj['present'] = Program.constructFromObject(data['present']);
            }
            if (data.hasOwnProperty('following')) {
                obj['following'] = Program.constructFromObject(data['following']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Program} previous
 */
GetProgramsNowOnAir200ResponseNowonairListG1.prototype['previous'] = undefined;

/**
 * @member {module:model/Program} present
 */
GetProgramsNowOnAir200ResponseNowonairListG1.prototype['present'] = undefined;

/**
 * @member {module:model/Program} following
 */
GetProgramsNowOnAir200ResponseNowonairListG1.prototype['following'] = undefined;






export default GetProgramsNowOnAir200ResponseNowonairListG1;

