/**
 * NHK API v2
 * A JavaScript client for NHK Program Guide API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListList from './ListList';

/**
 * The List model module.
 * @module model/List
 * @version 1.1.0
 */
class List {
    /**
     * Constructs a new <code>List</code>.
     * @alias module:model/List
     * @param list {module:model/ListList} 
     */
    constructor(list) { 
        
        List.initialize(this, list);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, list) { 
        obj['list'] = list;
    }

    /**
     * Constructs a <code>List</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/List} obj Optional instance to populate.
     * @return {module:model/List} The populated <code>List</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new List();

            if (data.hasOwnProperty('list')) {
                obj['list'] = ListList.constructFromObject(data['list']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ListList} list
 */
List.prototype['list'] = undefined;






export default List;

