/**
 * NHK API v2
 * A JavaScript client for NHK Program Guide API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Logo model module.
 * @module model/Logo
 * @version 1.1.2
 */
class Logo {
    /**
     * Constructs a new <code>Logo</code>.
     * @alias module:model/Logo
     * @param url {String} 
     * @param width {String} 
     * @param height {String} 
     */
    constructor(url, width, height) { 
        
        Logo.initialize(this, url, width, height);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, width, height) { 
        obj['url'] = url;
        obj['width'] = width;
        obj['height'] = height;
    }

    /**
     * Constructs a <code>Logo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Logo} obj Optional instance to populate.
     * @return {module:model/Logo} The populated <code>Logo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Logo();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'String');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} url
 */
Logo.prototype['url'] = undefined;

/**
 * @member {String} width
 */
Logo.prototype['width'] = undefined;

/**
 * @member {String} height
 */
Logo.prototype['height'] = undefined;






export default Logo;

