/**
 * NHK API v2
 * JavaScript client for NHK Program Guide API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NhkApiV2);
  }
}(this, function(expect, NhkApiV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NhkApiV2.ProgramsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProgramsApi', function() {
    describe('getProgramInfo', function() {
      it('should call getProgramInfo successfully', function(done) {
        //uncomment below and update the code to test getProgramInfo
        //instance.getProgramInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProgramsByChannel', function() {
      it('should call getProgramsByChannel successfully', function(done) {
        //uncomment below and update the code to test getProgramsByChannel
        //instance.getProgramsByChannel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProgramsByGenre', function() {
      it('should call getProgramsByGenre successfully', function(done) {
        //uncomment below and update the code to test getProgramsByGenre
        //instance.getProgramsByGenre(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProgramsNowOnAir', function() {
      it('should call getProgramsNowOnAir successfully', function(done) {
        //uncomment below and update the code to test getProgramsNowOnAir
        //instance.getProgramsNowOnAir(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
